### ISSUE TITLE
Publish Dev Image workflow fails: EventSequence tuple accessed via .clientId in roundtrip test

### ISSUE THREAD

**Issue by iameneko** [scs-lab/ChronoLog#674]
## Summary

The **Publish Dev Image** workflow has been failing on `develop` since #670 (run [26553233114](https://github.com/grc-iit/chronolog/actions/runs/26553233114)).

```
tests/integration/client/client_clientid_roundtrip_test.cpp:142:30: error:
'chronolog::EventSequence' {aka 'class std::tuple<long unsigned int, long unsigned int, unsigned int>'}
has no member named 'clientId'
  142 |         assert(ev.sequence().clientId == writer_id &&
```

`EventSequence` is a `typedef std::tuple<chrono_time, ClientId, chrono_index>` (`client/cpp/include/chronolog_types.h:25`), so `.clientId` was never valid.

## Why the introducing PR (#644) passed CI

- **Local Pipeline** and **Distributed Pipeline** build in **Release**, where glibc's `assert` macro expands to `((void)0)` and the expression is never compiled — the bad access is invisible.
- **Publish Dev Image** builds in **Debug** (`tools/deploy/build.sh -t Debug`), where `assert` compiles its argument and the type error surfaces.

The test file was introduced in #644 and not touched since; the dev-image run for #644 is listed as success but the next push (#670) failed on the same file, suggesting #644's Debug build may not have exercised this TU or was cached.

## Fix

Read the ClientId slot via `std::get<1>(ev.sequence())`. PR: #673.

## Follow-up worth considering

The fact that a Debug-only compile error slipped through three subsequent merges means the Debug build is effectively non-gating in practice. Worth deciding whether Publish Dev Image should block merges to `develop`, or whether one of the gating pipelines should also build Debug.
